#!C:\Users\Lenovo\OneDrive\Desktop\Internship_files\AutoML\backend\backend_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
